# Generated by Django 2.2.2 on 2019-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('fuel', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel')], max_length=10)),
            ],
        ),
    ]
